GolfSlayer/Controllers/InformationController.cs
using Repositories;
using Repositories.Database;
using Repositories.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GolfSlayer.Models;

namespace GolfSlayer.Controllers
{
    public class InformationController : BaseController
    {
        public ActionResult About()
        {
            return View();
        }

        public ActionResult AboutSH()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult Rules()
        {
            return View();
        }

        public ActionResult Sponsors()
        {
            return View();
        }
    }
}

GolfSlayer/Views/Shared/Partials/_PartialFooter.cshtml
<div class="benefiting-svg-wrapper">
    <img src="@Url.Content("~/Content/logos/benefitingSafeHomes.svg")" class="benefiting-svg" alt="benefiting">
</div>

GolfSlayer/Views/Shared/Partials/_PartialLeaderboard.cshtml
<div id="Leaderboard" class="tabContent">
    <h2 class="teamName">
        2015 Guardian Cup Leaderboard
    </h2>
    <table class="table whiteFont">
        <thead>
            <tr>
                <th class="text-center">Team Name</th>
                <th class="text-center">Score</th>
                <th class="text-center">Thru</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: leaderboardVM.TeamScores">
            <tr>
                <td class="text-center col-xs-4">
                    <h3 data-bind="text:TeamName"></h3>
                </td>
                <td class="text-center col-xs-4">
                    <h3 data-bind="text: ScoreDisplay, style: { color: ScoreDisplay() <= -1 ? 'red' : 'black' }"></h3>
                </td>
                <td class="text-center col-xs-4">
                    <h3 class="form-control" data-bind="text:Thru" style="max-width: 75px; margin: 0px auto;"></h3>
                </td>
            </tr>
        </tbody>
    </table>
</div>

GolfSlayer/Views/Shared/Partials/_PartialMessaging.cshtml
<div id="Messaging" class="tabContent">
    <div id="Controls">
        <select id="ChatRoomsSelect">
            <option value="">Choose A Chat Room:</option>
            <option value="GeneralChat">General Chat</option>
            <option value="AdminChat">Guardian Cup</option>
        </select>
    </div>
    <div id="ChatWindows" class="readableBG" style="padding: 2em;">
        <div id="GeneralChat" class="chatRoom" style="display:none;">
            <h3>General Chat</h3>
            <ul class="messagingWrapper"></ul>
            <div class="clearfix"></div>
        </div>
        <div id="AdminChat" class="chatRoom" style="display:none;">
            <h3>Messages From The Guardian Cup</h3>
            <ul class="messagingWrapper"></ul>
            <div class="clearfix"></div>
        </div>
        <div id="ChatInputControls" style="display:none;">
            <hr style="display: block; height: 1px; border: 0; border-top: 1px solid #ccc; margin: 1em 0; padding: 0;" />
            <div class="col-xs-12 col-sm-10 col-md-11">
                <input type="text" id="ChatInput" style="width: 100%;" />
            </div>
            <div class="col-xs-12 col-sm-2 col-md-1">
                <input type="button" id="ChatSubmit" value="Send" class="btn btn-success" style="width: 100%; padding: .25em 0; margin: .25em;" />
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#ChatRoomsSelect').change(function () {
            var room = $(this).find("option:selected").val();
            $(".chatRoom").hide();
            $("#ChatInputControls").hide();
            if (room != "") {
                $("#" + room).show();
                if((room == "AdminChat" && @Json.Encode(SessionVars.Item.Team.IsAdmin)) || (room != "AdminChat")) {
                    $("#ChatInputControls").show();
                }
            }
        });
    });
</script>
<script>
    $(function () {
        var chat = $.connection.chatHub;
        chat.client.addNewMessageToPage = function (name, message, room) {
            if(room == "AdminChat" && !@Json.Encode(SessionVars.Item.Team.IsAdmin)) {
                AdminMessage(htmlEncode(message));
            }
            addMessage(name,message,room);
        };
        chat.client.getCurrentMessages = function(Messages) {
            for(i = 0; i < Messages.length; i++) {
                addMessage(Messages[i].Name, Messages[i].Message, Messages[i].Room);
            }
        };
        function sendMessage() {
            var room = $("#ChatRoomsSelect").find("option:selected").val();
            var team = "@SessionVars.Item.Team.Name";
            var message = $("#ChatInput").val();
            if(message.length > 0) {
                chat.server.send(team, message, room);
            }
            $("#ChatInput").val('').focus();
        }
        function addMessage(name, message, room) {
            var liClass = ((name == "@SessionVars.Item.Team.Name") ? "leftChat" : "rightChat");
            $("#" + room + " ul").append("<li class='" + liClass + "'><strong>" + htmlEncode(name) + "</strong>: " + htmlEncode(message) + "</li>");
        }
        $.connection.hub.start().done(function () {
            chat.server.getCachedMessages();
            $("#ChatSubmit").click(function () {
                sendMessage();
            });
            $("#ChatInput").pressEnter(function() {
                sendMessage();
            });
        });
        });
</script>
<script type="text/javascript">

    function htmlEncode(value) {
        var encodedValue = $('<div />').text(value).html();
        return encodedValue;
    }
    $.fn.pressEnter = function(fn) {
        return this.each(function() {
            $(this).bind('enterPress', fn);
            $(this).keyup(function(e) {
                if(e.keyCode == 13)
                {
                    $(this).trigger("enterPress");
                }
            });
        });
    }
</script>

GolfSlayer/Views/Shared/Partials/_PartialNavbar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" style="padding: 5px 0px;">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink(" ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("More about The Guardian Cup", "About", "Information")</li>
                <li>@Html.ActionLink("More about SafeHomes", "AboutSH", "Information")</li>
                <li>@Html.ActionLink("Our Sponsors", "Sponsors", "Information")</li>
                <li>@Html.ActionLink("Tournament Rules", "Rules", "Information")</li>
                <li>@Html.ActionLink("Contact Us", "Contact", "Information")</li>
                <li>@Html.ActionLink("Sign Out", "SignOut", "Home")</li>
            </ul>
        </div>
    </div>
</div>

GolfSlayer/Views/Shared/Partials/_PartialPar3Entry.cshtml
<div id="Par3Entry" class="tabContent">
    Par 3
</div>

GolfSlayer/Views/Shared/Partials/_PartialScorecard.cshtml
<div id="Scorecard" class="tabContent">
    <h2 class="teamName">
        @SessionVars.Item.Team.Name
    </h2>
    <h2 class="totalScore">
        <span data-bind="text: scoresVM.totalScore, style: { color: scoresVM.totalScore() <= -1 ? 'red' : 'black' }"></span>
    </h2>
    <div class="row">
        <table class="table whiteFont">
            <tbody data-bind=" foreach: scoresVM.scores">
                <tr class="ScoreRow">
                    <td class="text-right" style="width:40%">
                        <span style="font-size:10px;">Hole</span> <span data-bind="text:HoleNumber"></span>
                    </td>
                    <td class="text-center" style="width:20%">
                        <input class="form-control" style="width:75px; padding:0 10px;" type="number" data-bind="value:Value, formatScore:Value, event: { blur: scoresVM.saveScore }, onEnterPress:scoresVM.saveScore" name="score" />
                    </td>
                    <td class="tet-left" style="width:40%">
                        <span data-bind="text:ParValueDisplay"></span>                                       
                    </td>
                </tr>
                <tr data-bind="visible: Closest.HasClosest">
                    <td colspan="3" class="text-center">
                        <span data-bind="text:Closest.ClosestName"></span>,: <span data-bind="text:Closest.ClosestDistanceDisplay"></span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
 @*<!-- ko if: Closest.HasClosest -->

<span data-bind="text:Closest.ClosestName"></span> - <span data-bind="text:Closest.ClosestDistanceDisplay"></span>
<!-- /ko -->*@        

GolfSlayer/Views/Shared/Partials/_PartialSubNav.cshtml
<ul id="pagenavigation">
    @if (SessionVars.Item.Team.IsAdmin)
    {
        <li class="col-xs-4"><a href="#Par3Entry" class="active"><i class="fa fa-map-pin"></i><br /><span>Scorecard</span></a></li>
        <li class="col-xs-4"><a href="#Leaderboard"><i class="fa fa-trophy"></i><br /><span>Leaderboard</span></a></li>
        <li class="col-xs-4"><a href="#Messaging"><i class="fa fa-bullhorn"></i><br /><span>Messaging</span></a></li>
    }
    else
    {
        <li class="col-xs-3"><a href="#Scorecard" class="active"><i class="fa fa-map-pin"></i><br /><span>Scorecard</span></a></li>
        <li class="col-xs-3"><a href="#Yardage"><i class="fa fa-map"></i><br /><span>Yardage</span></a></li>
        <li class="col-xs-3"><a href="#Leaderboard"><i class="fa fa-trophy"></i><br /><span>Leaderboard</span></a></li>
        <li class="col-xs-3"><a href="#Messaging"><i class="fa fa-bullhorn"></i><br /><span>Messaging</span></a></li>
    }
</ul>

<div class="clearfix"></div>

GolfSlayer/Views/Shared/Partials/_PartialYardage.cshtml
<div id="Yardage" class="tabContent">
    <img src="@Url.Content("~/Content/logos/exampleyardage.svg")" />
</div>